### ISSUE TITLE
Sink Is Creating New Log Files Within the Day With "_001" at the end

### ISSUE THREAD

**Issue by sunmorgus** [serilog/serilog-sinks-rollingfile#23]
I've currently got serilog set up in my Web API project to use the rolling file sink. It configures the logs in the Global.asax Application_Start like this:

```
        var webPath = HttpContext.Current.Server.MapPath("/logs/");
        var logLevel = ConfigurationManager.AppSettings.Get("LogLevel");

        switch (logLevel.ToLower())
        {
            case "warning":
                Log.Logger = new LoggerConfiguration()
                    .WriteTo.RollingFile(webPath + "BAH.API.Employee-{Date}.txt")
                    .MinimumLevel.Warning()
                    .CreateLogger();

                break;

            case "verbose":
                Log.Logger = new LoggerConfiguration()
                    .WriteTo.RollingFile(webPath + "BAH.API.Employee-{Date}.txt")
                    .MinimumLevel.Verbose()
                    .CreateLogger();

                break;

            case "information":
            default:
                Log.Logger = new LoggerConfiguration()
                    .WriteTo.RollingFile(webPath + "BAH.API.Employee-{Date}.txt")
                    .MinimumLevel.Information()
                    .CreateLogger();

                break;
        }
```

This works very well; however, there is one issue that I've been seeing... on occasion, it rolls the log file over and appends a "_001", "_002", etc. Is there a way to prevent this from happening? I thought at first that it had to do with the log files getting too big, but it'll sometimes roll them over when there is only a couple lines in there. Do I need to initialize the log file in a different way?

**Comment by nblumhardt** [comment]
Hi - thanks for the note. Yes, I think you need to grab version 3.0.0 of the sink and specify `shared: true` in the configuration, we've just added inter-process shared file support in #15.

Cheers!

**Comment by sunmorgus** [comment]
I've tried that I'm afraid, and while it may work, I get errors when trying to later read the log file (I have an endpoint in my API that allows me to get the contents of the log file, since the API is hosted out in Azure and I don't have easy access to it):

The process cannot access the file because it is being used by another process.

I'm using the following code to read the log file:

```

                    using (FileStream fs = new FileStream(logFile, FileMode.Open, FileAccess.Read, FileShare.ReadWrite))
                    {
                        using (StreamReader sr = new StreamReader(fs, Encoding.Default))
                        {
                            var log = sr.ReadToEnd();

                            var response = new HttpResponseMessage(System.Net.HttpStatusCode.OK);
                            response.Content = new StringContent(log, Encoding.UTF8, "text/plain");
                            return response;
                        }
                    }
```

**Comment by nblumhardt** [comment]
Thanks for the follow-up. Sounds like you need to update the version of the Serilog.Sinks.File that's in use - #20 was fixed recently in https://github.com/serilog/serilog-sinks-file/releases/tag/v3.0.1 but the NuGet package dependency version wasn't update here. Fixing that now.

Cheers,
Nick

**Comment by chic2013** [comment]
Hi,
Our project is using Serilog2.3.0, Serilog.Sinks.ColoredConsole 2.0.0, Serilog.Sinks.File 3.1.1, Serilog.Sinks.RollingFile 3.2.0. However, i still see that the log/verbose files created for a day have numbers _001, _002, _003 etc attached next to filename-Date.
The idea was to create a central logging web api but when i see these different versions of the files, it kind of negates the very purpose I am creating one. Should not different apps logging into this api be able to write into one single log file for a particular date?
Is there something I might be missing?

Thanks

**Comment by nblumhardt** [comment]
Hi @chic2013 - can you please open a fresh ticket with details showing exactly how you're configuring the logger? Thanks!

**Comment by chic2013** [comment]
Sure
